# yaml-language-server: $schema=public/schemas/brainhack-config.json
displaySections:
  tutorial: true
  schedule: true
cost: 5
location:
  name: Western Interdisciplinary Research Building
  street: Perth Dr
  city: London
  province: "ON"
  url: "https://www.uwo.ca/bmi/about/wirb.html"
  maps_id: ChIJCVSloavvLogR82_w3v729s0
organizers:
  - Ali Khan
  - Suzanne Witt
  - Dimunthu Henadeerage Don
  - Tristan Kuehn
  - Aidasadat Tafreshi
  - Priya Kalra
  - Charlotte Liang
  - Aria Fallah
  - Liam Bilbie
  - Matthew Little
  - Azadeh Jafari
  - Esmin Unaran
  - Derrick Xiang
  - Aishwarya Pathak
  - Sam Mestern
  - Farah Mushtaha
  - Peter Van Dyken
  - Naila Rahman
  - Brandon Hu
  - Aysha Motala
sponsors:
  - img: "/img/brainscan_logo.png"
    name: Brainscan
    url: "https://brainscan.uwo.ca"
  - img: "/img/western_logo.png"
    name: Western University
    url: "https://www.uwo.ca"
  - img: "/img/conp-pcno-logo.png"
    name: CONP-PCNO
    url: "https://conp.ca"
schedule:
  show: false
  startTime: 8
  endTime: 17
  days:
  - day: 1
    month: 12
    year: 2021
    events:
    - name: Breakfast
      time: "8:00"
      duration: "1:00"
    - name: Welcome & Project Pitches
      time: "9:00"
      duration: "1:30"
    - name: Hacking
      time: "10:30"
      duration: "1:30"
      color: red
    - name: Lunch
      time: "12:00"
      duration: "1:30"
    - name: MRI Data in Python
      time: "13:30"
      duration: "1:00"
      color: "#1f331e"
      id: python
      priority: 1
    - name: Intro to Datalad
      time: "14:30"
      duration: "1:30"
      color: "#1f331e"
      id: datalad
      priority: 1
    - name: Hacking
      time: "13:30"
      duration: "2:30"
      color: red
  - day: 2
    month: 12
    year: 2021
    events:
    - name: Breakfast
      time: "8:00"
      duration: "1:00"
    - name: fMRI/fMRIPrep
      time: "9:00"
      duration: "1:30"
      color: "#1f331e"
      id: frmi
      priority: 1
    - name: Introduction to Meta-analyses
      time: "10:30"
      duration: "1:30"
      color: "#1f331e"
      id: meta-analysis
      priority: 1
    - name: Lunch
      time: "12:00"
      duration: "1:30"
    - name: Intro to fNIRS
      time: "13:30"
      duration: "2:30"
      color: "#1f331e"
      id: fnirs
      priority: 1
    - name: Hacking
      time: "13:30"
      duration: "2:30"
      color: red
    - name: Hacking
      time: "9:00"
      duration: "3:00"
      color: red
    
  - day: 3
    month: 12
    year: 2021
    events:
    - name: Breakfast
      time: "8:00"
      duration: "1:00"
    - name: Intro to Machine Learning
      time: "9:00"
      duration: "1:30"
      color: "#1f331e"
      id: machine-learning
      priority: 1
    - name: Intro to Deep Learning
      time: "10:30"
      duration: "1:30"
      color: "#1f331e"
      id: deep-learning
      priority: 1
    - name: Lunch
      time: "12:00"
      duration: "1:30"
    - name: Hacking
      time: "9:00"
      duration: "3:00"
      color: red
    - name: Hacking
      time: "13:30"
      duration: "1:00"
      color: red
    - name: Project presentations & Wrap-up
      time: "14:30"
      duration: "1:30"
tutorials:
  - day: 1
    month: 12
    year: 2021
    tutorialTimes:
      - name: Afternoon
        options:
          - id: python
            name: Working with MRI Data in Python
            image: /img/python.png
            description: |
              This tutorial will teach one to manipulate and transform neuroimaging data
              using Python with commonly used. First, an understanding of how MRI data
              is represented in Python will be discussed followed by hands-on tasks such
              as basic manipulation of neuroimaging MRI data. All content will be
              performed using Jupyter notebooks in the spirit of reproducible and open
              science!
          - id: datalad
            name: Introduction to Datalad
            image: /img/datalad.png
  - day: 2
    month: 12
    year: 2021
    tutorialTimes:
      - name: Morning
        options:
          - id: frmi
            name: Introduction to fMRI
            image: /img/fmri.png
            description: |
              In this tutorial, minimally preprocessing of functional data using
              `fmriprep` will be discussed and the steps the tool performs. Following
              preprocessing, the data will be cleaned and made workable through motion
              cleaning and dimensionality reduction. The final component of the
              tutorials involves functional connectivity analysis. All content will be
              performed using Jupyter notebooks in the spirit of reproducible and open
              science! It is recommended (though not required) to attend the
              [Working with MRI Data in Python](#python) tutorial.
          - id: meta-analysis
            name: Introduction to Meta-analyses for Neuroimaging Data
            image: /img/review.png
      - name: Afternoon
        options:
          - id: fnirs
            name: Introduction to fNIRS
            image: /img/fnirs.png
            description: |
              In this session, you will get an overview of fNIRS (functional
              near-infrared spectroscopy), and see a live demonstration of fNIRS data
              acquisition and analysis. fNIRS is a relatively new neuroimaging method,
              that has gained in popularity over the last 20 years. fNIRS uses an array
              of light sensors on the surface of the scalp to detected oxygenated and
              deoxygenated bloodflow in cortex. fNIRS is low-cost, minimally invasive,
              offers reasonable spatial and temporal resolution, and is easily combined
              with other neuroimaging methods. In this session, we’ll discuss fNRIS
              methodology and applications, as well as the current state of affairs for
              fNIRS analysis.
  - day: 3
    month: 12
    year: 2021
    tutorialTimes:
      - name: Morning
        options:
          - id: machine-learning
            name: Machine Learning
            image: /img/machine-learning.png
          - id: deep-learning
            name: Introduction to Deep Learning
            image: /img/deep-learn.png
            description: |
              This tutorial will be broken up into a theoretical (~1hr) and practical
              component (~2hr). The theoretical component will provide:
                1) A basic overview of neural networks (NNs) and backpropagation, 
                2) An overview of several key NN architectures including convolutional 
                   and recurrent networks, 
                3) An open discussion of active areas of NN research. 

              The practical component of this tutorial will focus on hands-on experience
              with Tensorflow. Topics will include 
                1) Organization of code into classes, functions, and the Tensorgraph, 
                2) Examples of dense and convolutional networks for real problems using 
                   high-level Tensorflow tools such as built-in Keras functions, 
                3) An open session for exploring and adapting existing NNs or for 
                   helping attendees build their own networks.
    
    
