# yaml-language-server: $schema=./public/schemas/brainhack-config.json
location:
  name: Western Interdisciplinary Research Building
  street: Perth Dr
  city: London
  province: "ON"
  url: "https://www.uwo.ca/bmi/about/wirb.html"
  maps_id: ChIJCVSloavvLogR82_w3v729s0
organizers:
  - Ali Khan
  - Suzanne Witt
  - Dimunthu Henadeerage Don
  - Tristan Kuehn
  - Aidasadat Tafreshi
  - Priya Kalra
  - Charlotte Liang
  - Aria Fallah
  - Liam Bilbie
  - Matthew Little
  - Azadeh Jafari
  - Esmin Unaran
  - Derrick Xiang
  - Aishwarya Pathak
  - Sam Mestern
  - Farah Mushtaha
  - Peter Van Dyken
  - Naila Rahman
  - Brandon Hu
  - Aysha Motala
sponsors:
  - img: "/img/brainscan_logo.png"
    name: Brainscan
    url: "https://brainscan.uwo.ca"
  - img: "/img/western_logo.png"
    name: Western University
    url: "https://www.uwo.ca"
  - img: "/img/conp-pcno-logo.png"
    name: CONP-PCNO
    url: "https://conp.ca"
schedule:
  show: false
  startTime: 8
  endTime: 18
  days:
  - day: 1
    month: 12
    year: 2021
    events:
    - name: Check-in
      time: "8:00"
      duration: "1:00"
    - name: Welcome & Intro
      time: "9:00"
      duration: "1:00"
    - name: Project Pitches
      time: "10:00"
      duration: "2:00"
    - name: Lunch
      time: "12:00"
      duration: "1:00"
    - name: Intro to Image Manipulation
      time: "13:00"
      duration: "1:30"
    - name: Intro to fMRI and EEG
      time: "14:30"
      duration: "2:00"
    - name: Unconference
      time: "16:30"
      duration: "1:00"
  - day: 2
    month: 12
    year: 2021
    events:
    - name: Breakfast
      time: "8:00"
      duration: "2:00"
    - name: Intro to Deep Learning
      time: "10:00"
      duration: "1:30"
    - name: "TWINtalks: Blake Richards"
      time: "11:30"
      duration: "1:00"
    - name: Lunch & Unconference
      time: "12:30"
      duration: "1:00"
    - name: Deep Learning Practical
      time: "13:30"
      duration: "2:00"
    - name: Intro to DTI
      time: "15:30"
      duration: "1:30"
    - name: Social
      time: "17:00"
      duration: "1:00"
  - day: 3
    month: 12
    year: 2021
    events:
    - name: Breakfast
      time: "8:00"
      duration: "1:00"
    - name: Intro to fNIRS
      time: "9:00"
      duration: "3:00"
    - name: Lunch & Unconference
      time: "12:00"
      duration: "1:00"
    - name: TBA
      time: "13:00"
      duration: "2:30"
    - name: Project presentations & Wrap-up
      time: "15:30"
      duration: "1:30"
tutorials:
  - day: 1
    month: 12
    year: 2021
    tutorialTimes:
      - name: Afternoon
        options:
          - name: Working with MRI Data in Python
            image: /img/python.png
            description: |
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
              tempor incididunt ut labore et dolore magna aliqua. Enim diam vulputate ut
              pharetra sit amet aliquam id. Donec ac odio tempor orci dapibus ultrices
              in iaculis. Sit amet cursus sit amet dictum sit amet justo.
          - name: Introduction to Datalad
            image: /img/datalad.png
            description: |
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
              tempor incididunt ut labore et dolore magna aliqua. Enim diam vulputate ut
              pharetra sit amet aliquam id. Donec ac odio tempor orci dapibus ultrices
              in iaculis. Sit amet cursus sit amet dictum sit amet justo.
  - day: 2
    month: 12
    year: 2021
    tutorialTimes:
      - name: Morning
        options:
          - name: Introduction to fMRI
            image: /img/frmi.png
            description: |
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
              tempor incididunt ut labore et dolore magna aliqua. Enim diam vulputate ut
              pharetra sit amet aliquam id. Donec ac odio tempor orci dapibus ultrices
              in iaculis. Sit amet cursus sit amet dictum sit amet justo.
          - name: Introduction to Meta-analyses for Neuroimaging Data
            image: /img/review.png
            description: |
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
              tempor incididunt ut labore et dolore magna aliqua. Enim diam vulputate ut
              pharetra sit amet aliquam id. Donec ac odio tempor orci dapibus ultrices
              in iaculis. Sit amet cursus sit amet dictum sit amet justo.
      - name: Afternoon
        options:
          - name: Introduction to fNIRS
            image: /img/fnirs.png
            description: |
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
              tempor incididunt ut labore et dolore magna aliqua. Enim diam vulputate ut
              pharetra sit amet aliquam id. Donec ac odio tempor orci dapibus ultrices
              in iaculis. Sit amet cursus sit amet dictum sit amet justo.
  - day: 3
    month: 12
    year: 2021
    tutorialTimes:
      - name: Morning
        options:
          - name: Machine Learning
            image: /img/machine-learning.png
            description: |
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
              tempor incididunt ut labore et dolore magna aliqua. Enim diam vulputate ut
              pharetra sit amet aliquam id. Donec ac odio tempor orci dapibus ultrices
              in iaculis. Sit amet cursus sit amet dictum sit amet justo.
          - name: Introduction to Deep Learning
            image: /img/deep-learn.png
            description: |
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
              tempor incididunt ut labore et dolore magna aliqua. Enim diam vulputate ut
              pharetra sit amet aliquam id. Donec ac odio tempor orci dapibus ultrices
              in iaculis. Sit amet cursus sit amet dictum sit amet justo.
    
    
