location:
  name: Western Interdisciplinary Research Building
  street: Perth Dr
  city: London
  province: "ON"
  url: "https://www.uwo.ca/bmi/about/wirb.html"
  maps_id: ChIJCVSloavvLogR82_w3v729s0
organizers:
  - Ali Khan Marieke Mur
  - Olivia Stanley
  - Jason Kai
  - Suzanne Witt
  - Kasey Van Hedger
  - Aysha Motala
  - Geoffrey Ngo
  - Emma Stewart
  - Justine Clery
  - Claire Park
  - Dimuthu Hemachandra
  - Geetika Gupta
  - Cat Fleury
  - Eva Berlot
sponsors:
  - img: "/img/brainscan_logo.png"
    name: Brainscan
    url: "https://brainscan.uwo.ca"
  - img: "/img/western_logo.png"
    name: Western University
    url: "https://www.uwo.ca"
  - img: "/img/conp-pcno-logo.png"
    name: CONP-PCNO
    url: "https://conp.ca"
schedule:
  startTime: 8
  endTime: 18
  days:
  - day: 1
    month: 12
    year: 2021
    events:
    - name: Check-in
      time: "8:00"
      duration: "1:00"
    - name: Welcome & Intro
      time: "9:00"
      duration: "1:00"
    - name: Project Pitches
      time: "10:00"
      duration: "2:00"
    - name: Lunch
      time: "12:00"
      duration: "1:00"
    - name: Intro to Image Manipulation
      time: "13:00"
      duration: "1:30"
    - name: Intro to fMRI and EEG
      time: "14:30"
      duration: "2:00"
    - name: Unconference
      time: "16:30"
      duration: "1:00"
  - day: 2
    month: 12
    year: 2021
    events:
    - name: Breakfast
      time: "8:00"
      duration: "2:00"
    - name: Intro to Deep Learning
      time: "10:00"
      duration: "1:30"
    - name: "TWINtalks: Blake Richards"
      time: "11:30"
      duration: "1:00"
    - name: Lunch & Unconference
      time: "12:30"
      duration: "1:00"
    - name: Deep Learning Practical
      time: "13:30"
      duration: "2:00"
    - name: Intro to DTI
      time: "15:30"
      duration: "1:30"
    - name: Social
      time: "17:00"
      duration: "1:00"
  - day: 3
    month: 12
    year: 2021
    events:
    - name: Breakfast
      time: "8:00"
      duration: "1:00"
    - name: Intro to fNIRS
      time: "9:00"
      duration: "3:00"
    - name: Lunch & Unconference
      time: "12:00"
      duration: "1:00"
    - name: TBA
      time: "13:00"
      duration: "2:30"
    - name: Project presentations & Wrap-up
      time: "15:30"
      duration: "1:30"
