name: Project Pitch
description: Pitch a project for the upcoming Western Brainhack!
title: '[Pitch]: '
labels: ['pitch']
body:
  - type: markdown
    attributes:
      value: >
        Thank you for submitting a project to Brainhack Western! As a project
        lead, you'll be competing with a team of hackers on a neuroscience
        project. Your project can be anything you want, with just two general
        guidelines:

        - Your project should be broadly neuroscience related.

        - Your project should contribute to open science. This depends a bit on
          your project, but may mean:

          - Any code you write is publicly available on github (or an
            equivalent)

          - Datasets you collect or process are publicly available (assuming
            you have the appropriate ethics approvals)

        Other than that, the sky's the limit! If you have any questions, feel
        free to reach out and ask (email us at `brainhack.western@gmail.com`).
        Or check out [previous
        projects](https://brainhackwestern.github.io/projects/2022) for
        inspiration.

        At the Brainhack opening ceremony (typically 9am on the first day), you
        will pitch your project to all the attendees, encouraging them to join
        your team. Pitches will be 2-minute elevator style, with no slides.
        Please ensure one of the leads is able to attend the pitch: projects
        that aren't pitched typically don't get off the ground.

        As part of your project description, you may specify certain skills
        (e.g. python, git, neuroimaging, etc) that will be used in your project.
        However, all brainhack teams must be open to anyone who wants to join
        regardless of their level of knowledge. As a project lead, part of your
        responsibility is to teach and guide those with less technical
        experience than yourself.

        Finally, before you continue, be sure to
        [register](https://brainhackwestern.github.io/forms/registration) for
        the event.
  - type: input
    id: title
    attributes:
      label: Title
      description: Title of your project
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
         Describe your project in less than 150 words. You can use
         github-flavoured markdown syntax
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Project url
      description: >
        Link to a github repository or other source for project information
  - type: textarea
    id: organizers
    attributes:
      label: Project Leads
      description: >
        Names of the people pitching and organizing the project. Please enter
        one name per line. Following your name, please put your github username
        in parentheses, if you have one
      placeholder: Brain Hacker (@BrainhackWestern)
    validations:
      required: true
