name: Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - name: Update env for production
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          if [[ $REPO_NAME == 'BrainhackWestern.github.io' ]]; then
            
            echo NEXT_PUBLIC_URL='' > .env.production.local
            echo NEXT_PUBLIC_MAPS_EMBED_API_KEY=AIzaSyAfZCgUDCHkwhPMwFnT2xl1DdnyZmR334Q >> .env.production.local
            echo Running on Production 
          else
            echo Running on stage
          fi
      - name: Build App
        run: npm run gh-build
      - name: Push git subdirectory as branch
        uses: s0/git-publish-subdir-action@v2.5.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true

